version: '3.3'
services:
  haproxy_layer_7:
    image: haproxy:2.6-alpine
    ports:
      - 8089:8089
    ulimits:
      nproc: 65535
      nofile:
        soft: 200000
        hard: 200000
    volumes:
      - ./haproxy/haproxy-layer-7.cfg:/usr/local/etc/haproxy/haproxy.cfg
    links:
      - backend0

  backend0:
    build:
      context: ./GolangBackend

networks:
  lb_l7_local:
    driver: bridge
